baseURL = 'https://fios.netlify.app'
languageCode = 'gl'
title = 'fios'
buildFuture = true
logo = "favicon.ico"


[menu]
  [[menu.main]]
  name = " Principal"
  url = "/"
  weight = 1
  [menu.main.params]
  reducido = "ğŸ§µ"

  [[menu.main]]
  name = " Biblioteca"
  url = "/biblioteca/"
  weight = 2
  [menu.main.params]
  reducido = "ğŸ“š"

  [[menu.main]]
  name = " OrganizaciÃ³ns"
  url = "/organizacions/"
  weight = 3
  [menu.main.params]
  reducido = "âœŠ"

  [[menu.main]]
  name = " Espazos"
  url = "/espazos/"
  weight = 4
  [menu.main.params]
  reducido = "ğŸ "

  [[menu.main]]
  name = " Calendario"
  url = "/calendario/"
  weight = 5
  [menu.main.params]
  reducido = "ğŸ—“ï¸"

  [[menu.main]]
  name = " Convocatorias"
  url = "/convocatorias/"
  weight = 6
  [menu.main.params]
  reducido = "ğŸ“£"

  [[menu.main]]
  name = " Podcast"
  url = "/podcast/"
  weight = 7
  [menu.main.params]
  reducido = "ğŸ™ï¸"

  [[menu.main]]
  name = " Redes"
  url = "/redes/"
  weight = 8
  [menu.main.params]
  reducido = "#ï¸âƒ£"

  [[menu.main]]
  name = " Recursos"
  url = "/recursos/"
  weight = 9
  [menu.main.params]
  reducido = "â•"


[params]
  sidebarmode = "reduced"

buildFuture = true