baseURL = 'https://fios.netlify.app'
title = 'fios'
buildFuture = true
logo = "favicon.ico"

defaultContentLanguage = "rag"
defaultContentLanguageInSubdir = true

[languages]
  [languages.rag]
    languageName = "RAG"
    weight = 1  
    [languages.rag.menu]
      [[languages.rag.menu.main]]
      name = " Principal"
      url = "/rag/"
      weight = 1
      [languages.rag.menu.main.params]
      translatedURL = "/agal/"
      reducido = "ğŸ§µ"

      [[languages.rag.menu.main]]
      name = " Biblioteca"
      url = "/rag/biblioteca/"
      weight = 2
      [languages.rag.menu.main.params]
      translatedURL = "/agal/biblioteca/"
      reducido = "ğŸ“š"

      [[languages.rag.menu.main]]
      name = " OrganizaciÃ³ns"
      url = "/rag/organizacions/"
      weight = 3
      [languages.rag.menu.main.params]
      translatedURL = "/agal/organizaÃ§ons/"
      reducido = "âœŠ"

      [[languages.rag.menu.main]]
      name = " Espazos"
      url = "/rag/espazos/"
      weight = 4
      [languages.rag.menu.main.params]
      translatedURL = "/agal/espaÃ§os/"
      reducido = "ğŸ "

      [[languages.rag.menu.main]]
      name = " Calendario"
      url = "/rag/calendario/"
      weight = 5
      [languages.rag.menu.main.params]
      translatedURL = "/agal/calendario/"
      reducido = "ğŸ—“ï¸"

      [[languages.rag.menu.main]]
      name = " Convocatorias"
      url = "/rag/convocatorias/"
      weight = 6
      [languages.rag.menu.main.params]
      translatedURL = "/agal/convocatorias/"
      reducido = "ğŸ“£"

      [[languages.rag.menu.main]]
      name = " Podcast"
      url = "/rag/podcast/"
      weight = 7
      [languages.rag.menu.main.params]
      translatedURL = "/agal/podcast/"
      reducido = "ğŸ™ï¸"

      [[languages.rag.menu.main]]
      name = " Redes"
      url = "/rag/redes/"
      weight = 8
      [languages.rag.menu.main.params]
      translatedURL = "/agal/redes/"
      reducido = "#ï¸âƒ£"

      [[languages.rag.menu.main]]
      name = " Recursos"
      url = "/rag/recursos/"
      weight = 9
      [languages.rag.menu.main.params]
      translatedURL = "/agal/recursos/"
      reducido = "â•"

      [[languages.rag.menu.mobil]]
      name = " Biblioteca"
      url = "/rag/biblioteca/"
      weight = 3
      [languages.rag.menu.mobil.params]
      translatedURL = "/agal/biblioteca/"
      imaxe = "/images/elementos/biblioteca.jpg"

      [[languages.rag.menu.mobil]]
      name = " Organizacions"
      url = "/rag/organizacions/"
      weight = 2
      [languages.rag.menu.mobil.params]
      translatedURL = "/agal/organizaÃ§ons/"
      imaxe = "/images/elementos/organizacions.jpg"

      [[languages.rag.menu.mobil]]
      name = " Principal"
      url = "/rag/"
      weight = 4
      [languages.rag.menu.mobil.params]
      translatedURL = "/agal/"
      imaxe = "/images/elementos/logo_icona.png"

      [[languages.rag.menu.mobil]]
      name = "Espazos"
      url = "/rag/espazos/"
      weight = 5
      [languages.rag.menu.mobil.params]
      translatedURL = "/agal/espaÃ§os/"
      imaxe = "/images/elementos/espazos.jpg"

      [[languages.rag.menu.mobil]]
      name = "Calendario"
      url = "/rag/calendario/"
      weight = 6
      [languages.rag.menu.mobil.params]
      translatedURL = "/agal/calendario/"
      imaxe = "/images/elementos/calendario.jpg"



[languages.agal]
  languageName = "AGAL"
  weight = 2
[languages.agal.menu]
  [[languages.agal.menu.main]]
  name = " Principal"
  url = "/agal/"
  weight = 1
  [languages.agal.menu.main.params]
  translatedURL = "/rag/"
  reducido = "ğŸ§µ"

  [[languages.agal.menu.main]]
  name = " Biblioteca"
  url = "/agal/biblioteca/"
  weight = 2
  [languages.agal.menu.main.params]
  translatedURL = "/rag/biblioteca/"
  reducido = "ğŸ“š"

  [[languages.agal.menu.main]]
  name = " OrganizaÃ§ons"
  url = "/agal/organizaÃ§ons/"
  weight = 3
  [languages.agal.menu.main.params]
  translatedURL = "/rag/organizacions/"
  reducido = "âœŠ"

  [[languages.agal.menu.main]]
  name = " EspaÃ§os"
  url = "/agal/espaÃ§os/"
  weight = 4
  [languages.agal.menu.main.params]
  translatedURL = "/rag/espazos/"
  reducido = "ğŸ "

  [[languages.agal.menu.main]]
  name = " CalendÃ¡rio"
  url = "/agal/calendario/"
  weight = 5
  [languages.agal.menu.main.params]
  translatedURL = "/rag/calendario/"
  reducido = "ğŸ—“ï¸"

  [[languages.agal.menu.main]]
  name = " ConvocatÃ³rias"
  url = "/agal/convocatorias/"
  weight = 6
  [languages.agal.menu.main.params]
  translatedURL = "/rag/convocatorias/"
  reducido = "ğŸ“£"

  [[languages.agal.menu.main]]
  name = " Podcast"
  url = "/agal/podcast/"
  weight = 7
  [languages.agal.menu.main.params]
  translatedURL = "/rag/podcast/"
  reducido = "ğŸ™ï¸"

  [[languages.agal.menu.main]]
  name = " Redes"
  url = "/agal/redes/"
  weight = 8
  [languages.agal.menu.main.params]
  translatedURL = "/rag/redes/"
  reducido = "#ï¸âƒ£"

  [[languages.agal.menu.main]]
  name = " Recursos"
  url = "/agal/recursos/"
  weight = 9
  [languages.agal.menu.main.params]
  translatedURL = "/rag/recursos/"
  reducido = "â•"

  [[languages.agal.menu.main.mobil]]
  name = " Biblioteca"
  url = "/agal/biblioteca/"
  weight = 2
  [languages.agal.menu.main.mobil.params]
  translatedURL = "/agal/biblioteca/"
  reducido = "ğŸ“š"



[params]
  sidebarmode = "reduced"